version: "3.9"

services:
  ze-calculei:
    build: .
    container_name: ze-calculei
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ze-net

  redis:
    image: redis:7-alpine
    container_name: ze-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ze-net

networks:
  ze-net:
    driver: bridge
